version: "3.2"
services:
  db:
    image: missinglink/spatialite

  pdv-api:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "8000:8000"
    links:
      - db

    command: >
          bash -c "make requirements-development &&
           make test &&
           make check-security-issues &&
           make lint &&
           make runserver-development"